object Dependencies {

    const val coreKtx = "androidx.core:core-ktx:${Versions.coreKtx}"
    const val appcompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    const val material = "com.google.android.material:material:${Versions.material}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    const val viewModelLifecycle = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle}"
    const val liveDataLifecycle = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.lifecycle}"
    const val activityX = "androidx.activity:activity-ktx:${Versions.activityX}"
    const val circularImageView = "de.hdodenhof:circleimageview:${Versions.circularImageView}"
    const val retrofit = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    const val gson = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    const val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    const val hilt = "com.google.dagger:hilt-android:${Versions.hilt}"
    const val hiltCompiler = "com.google.dagger:hilt-android-compiler:${Versions.hilt}"
    const val okHttpLoggingInterceptor =
        "com.squareup.okhttp3:logging-interceptor:${Versions.okHttpLoggingInterceptor}"
    const val dotsIndicator = "com.tbuonomo:dotsindicator:${Versions.dotsIndicator}"
    const val dataStorePref = "androidx.datastore:datastore-preferences:${Versions.dataStorePref}"
    const val dataStorePrefCore = "androidx.datastore:datastore-preferences-core:${Versions.dataStorePref}"
    const val navigationUi = "androidx.navigation:navigation-ui-ktx:${Versions.navigation}"
    const val navigationFragment = "androidx.navigation:navigation-fragment-ktx:${Versions.navigation}"
    const val rtc = "io.agora.rtc:full-sdk:${Versions.rtc}"
    const val sdp = "com.intuit.sdp:sdp-android:${Versions.sdp}"
    const val shimmer = "com.facebook.shimmer:shimmer:${Versions.shimmer}"
    const val swipeToRefresh = "androidx.swiperefreshlayout:swiperefreshlayout:${Versions.swipeToRefresh}"
    const val places = "com.google.android.libraries.places:places:${Versions.places}"
    const val firebaseMessaging = "com.google.firebase:firebase-messaging-ktx:${Versions.firebaseMessaging}"
    const val firebaseAnalytics = "com.google.firebase:firebase-analytics-ktx"
    const val groupie = "com.github.lisawray.groupie:groupie:${Versions.groupie}"
    const val groupieViewBinding = "com.github.lisawray.groupie:groupie-viewbinding:${Versions.groupie}"
    const val chatSdk  = "io.agora.rtc:chat-sdk:${Versions.chat}"
    const val pinView = "com.github.GoodieBag:Pinview:${Versions.pinView}"
    const val billingClient = "com.android.billingclient:billing:${Versions.billingClient}"
    const val appUpdate = "com.google.android.play:app-update:${Versions.appUpdate}"
    const val appUpdateKtx = "com.google.android.play:app-update-ktx:${Versions.appUpdate}"
    const val facebookSdk = "com.facebook.android:facebook-android-sdk:${Versions.facebookSdk}"

}