object Versions {

    const val coreKtx = "1.7.0"
    const val appCompat = "1.5.1"
    const val activityX = "1.5.1"
    const val material = "1.6.1"
    const val navigation = "2.5.3"
    const val constraintLayout = "2.1.4"
    const val lifecycle = "2.5.1"
    const val circularImageView = "3.1.0"
    const val glide = "4.11.0"
    const val retrofit = "2.9.0"
    const val okHttpLoggingInterceptor = "4.9.0"
    const val hilt = "2.55"
    const val dotsIndicator = "4.3"
    const val dataStorePref = "1.0.0"
    const val rtc = "4.6.0"
    const val sdp = "1.1.0"
    const val shimmer = "0.5.0"
    const val swipeToRefresh = "1.1.0"
    const val scratchView = "1.9.1"
    const val payment = "1.6.26"
    const val places = "3.0.0"
    const val firebaseMessaging = "23.0.3"
    const val groupie = "2.10.1"
    const val chat = "1.3.1"
    const val paging = "3.1.1"
    const val liveReactions = "1.0"
    const val pinView = "v1.5"
    const val billingClient = "7.1.1"
    const val appUpdate = "2.1.0"
    const val facebookSdk = "18.0.1"

    // testing versions
    const val junit = "4.13.2"
    const val junitExt = "1.1.3"
    const val espressoCore = "3.4.0"
}